// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa3wuZFVCcRplo5uutblEsFINw2J1KfIo',
    appId: '1:857007919036:web:4a7154c71311c83695a5b9',
    messagingSenderId: '857007919036',
    projectId: 'cliq-f3d88',
    authDomain: 'cliq-f3d88.firebaseapp.com',
    storageBucket: 'cliq-f3d88.firebasestorage.app',
    measurementId: 'G-PWQLS0120Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALEhrQaUE6yMW_0EnA_Lbf4nwhdzt568E',
    appId: '1:857007919036:android:f35c04ac3fa8464d95a5b9',
    messagingSenderId: '857007919036',
    projectId: 'cliq-f3d88',
    storageBucket: 'cliq-f3d88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCViCfFyIl2LOF29PdWNGxdaD_6SlgbPVM',
    appId: '1:857007919036:ios:49d8474e04e7fc5895a5b9',
    messagingSenderId: '857007919036',
    projectId: 'cliq-f3d88',
    storageBucket: 'cliq-f3d88.firebasestorage.app',
    iosBundleId: 'com.example.cobrosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCViCfFyIl2LOF29PdWNGxdaD_6SlgbPVM',
    appId: '1:857007919036:ios:49d8474e04e7fc5895a5b9',
    messagingSenderId: '857007919036',
    projectId: 'cliq-f3d88',
    storageBucket: 'cliq-f3d88.firebasestorage.app',
    iosBundleId: 'com.example.cobrosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa3wuZFVCcRplo5uutblEsFINw2J1KfIo',
    appId: '1:857007919036:web:091a38f0a6ad404b95a5b9',
    messagingSenderId: '857007919036',
    projectId: 'cliq-f3d88',
    authDomain: 'cliq-f3d88.firebaseapp.com',
    storageBucket: 'cliq-f3d88.firebasestorage.app',
    measurementId: 'G-8446QJK1G3',
  );
}
